### ISSUE TITLE
SuperAnnotate_OAK_YOLOv4 notebook - number of shave compile

### ISSUE THREAD

**Issue by Erol444** [superannotateai/model-deployment-tutorials#1]
Hello all,
as user pointed out in Luxonis' [forum](https://discuss.luxonis.com/d/202-using-a-custom-trained-blob-file-with-gen2/5), there is an issue with the [SuperAnnotate_OAK_YOLOv4](https://github.com/superannotateai/model-deployment-tutorials/blob/main/OAK/SuperAnnotate_OAK_YOLOv4_tiny_Deployment.ipynb) notebook.

```
payload = {
    'compile_type': 'myriad', 
    'compiler_params': '-ip U8 -VPU_MYRIAD_PLATFORM VPU_MYRIAD_2480 -VPU_NUMBER_OF_SHAVES 14 -VPU_NUMBER_OF_CMX_SLICES 14'
}
```
Model shouldn't be compiled for 14 shaves, but ~6 for best performance.
Thanks!

**Comment by ero1311** [comment]
@Erol444 fixed, thanks!
